### ISSUE TITLE
Update to the latest stable release

### ISSUE THREAD

**Issue by ghisvail** [docker/docker-snap#28]
The version in the `stable` channel is `17.06.2` whilst the version in the Ubuntu repository is `17.12.0`. Please consider upgrading the snap package to match the current stable release.

**Comment by psftw** [comment]
The Snap package is an experimental install path that does not receive the same level of validation and testing that the Debian packages do.  There are discussions between Docker, Inc and Canonical, Ltd to figure out the support details, and in the meantime we are not pushing new releases.   For now I would suggest installing via instructions at https://docs.docker.com/engine/installation/ to get the latest Docker CE (or EE).  Sorry for the inconvenience.

**Comment by ghisvail** [comment]
@psftw Is this discussion happening somewhere in the open, or behind closed doors? Users such as myself might want to provide perspectives on the appeal of snap packages for their respective use cases.

I personally appreciate `snap` providing centralized access to the most popular devops tools, including Docker and Kubernetes. It's just a shame the current version of Docker available in the snap store is lagging so much behind.

Since canonical is able to provide an up-to-date distribution of Kubernetes via snap, I believe Docker Inc. could achieve the same level of service for Docker.

**Comment by BlueT** [comment]
Any further info / updates?
The snap package is kinda old...

https://snapcraft.io/docker
- stable 17.06.2-ce
- candidate 17.06.2-ce
- beta 17.09.1-ce
- edge 17.03.1-ce-1 (what?!)

**Comment by favadi** [comment]
In the mean time maybe the snap version should be removed or users might end up with a unsupported version of docker.

**Comment by psftw** [comment]
Closing per updated README:
> The Docker Snap is no longer maintained by Docker, Inc. The last release version was 17.06.2 and will not be updated. The future of the Docker Snap is unclear, but it won't be developed here going forward. This repository will redirect to its new home if one will exist.
