### ISSUE TITLE
LD_LIBRARY_PATH is set in docker container

### ISSUE THREAD

**Issue by gitEmporer** [docker/docker-snap#30]
In a dockerfile if have to set the LD_LIBRARY_PATH, like: 
```
ENV LD_LIBRARY_PATH /opt/myComponent/lib  #ignored
ENV TestVariable TestDay # visible in container
```

But in the started container the environment variable isn't set.
How to fix this?

**Comment by ktsakalozos** [comment]
Do we know why this happens? Looks similar to the setuid behavior where LD_LIBRARY_PATH is unset. Here is how to repro:

```
docker run jupyterhub/jupyterhub:0.8.1
```

The following will not set LD_LIBRARY_PATH
```
sudo docker run  -e "LD_LIBRARY_PATH=foo" jupyterhub/jupyterhub:0.8.1 env
```

**Comment by jdstrand** [comment]
FYI, the issue was diagnosed here: https://forum.snapcraft.io/t/ld-library-path-in-snapped-docker/6903/16

**Comment by psftw** [comment]
Closing all issues and pull requests since this repo is getting archived (see notice at the top of README).
