### ISSUE TITLE
git is missing from docker-snap

### ISSUE THREAD

**Issue by arno01** [docker/docker-snap#32]
docker snap is missing git binary. Is it planned to add it? Or maybe use some kind of snap extensions if there are any?

The following should work:

```
$ docker build -t gopass github.com/gopasspw/gopass#master
unable to prepare context: unable to find 'git': exec: "git": executable file not found in $PATH
```

**Comment by AnderssonPeter** [comment]
I'm having the exact same issue, but when using docker-compose, did you find a solution for this?

**Comment by anonymouse64** [comment]
Hi, I have pushed a new version of the docker snap to the edge channel that includes git. I am now able to run your example command sucessfully. Please try out the edge channel and let me know if it works for you. You can do that by running:

```
sudo snap refresh docker --edge
```
The changes in the edge channel should show up in stable in a short while.

**Comment by psftw** [comment]
Closing all issues and pull requests since this repo is getting archived (see notice at the top of README).
