### ISSUE TITLE
When will the new versions of CE docker in SNAP be available?

### ISSUE THREAD

**Issue by huezo** [docker/docker-snap#33]
When will the new versions of CE docker in SNAP be available?
for example 18.05.0-ce or higher

[https://github.com/docker/docker-ce/releases](https://github.com/docker/docker-ce/releases)

:+1:  :smile:  :smiley:

**Comment by psftw** [comment]
Just updated readme -- we (Docker, Inc) will not be releasing a new Docker Snap.  Indeed the existing version is quite outdated at this point.  The future of the project is unclear.

**Comment by julian-alarcon** [comment]
Hey @huezo maybe you want to check this: https://forum.snapcraft.io/t/the-future-of-the-docker-snap/7218/19
