### ISSUE TITLE
libjli.so not found

### ISSUE THREAD

**Issue by robbybooker** [docker/docker-snap#42]
I've no idea if this is an issue with the docker snap or the docker image that I'm trying to use, but I'll ask here first. I'm trying to use container expert360/elasticmq. When I run:

docker run -p 9324:9324 expert360/elasticmq

I get this error:

me@moo:~$ docker run -p 9324:9324 expert360/elasticmq
java: error while loading shared libraries: libjli.so: cannot open shared object file: No such file or directory

I **don't** get this error when docker has been installed using apt. According to the Docker file the docker does use Java https://github.com/expert360/docker-elasticmq/blob/master/Dockerfile but I don't understand why a Java error is being surfaced outside of the container. 

I'm on elementaryOS Juno (18.04) but I also tried on Loki and vanilla Ubuntu 18.04 and the error occurs on all three.

Any ideas?

**Comment by psftw** [comment]
Closing all issues and pull requests since this repo is getting archived (see notice at the top of README).
